services:
  - type: web
    name: beckend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --no-input
    startCommand: gunicorn Uzmovi.wsgi:application

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: beckend.settings
      - key: SECRET_KEY
        value: django-insecure-...
      - key: DEBUG
        value: 'False'